
import React from 'react';

export const COLORS = {
  RED: 'bg-red-500 shadow-red-500/50',
  BLUE: 'bg-blue-500 shadow-blue-500/50',
  GREEN: 'bg-emerald-500 shadow-emerald-500/50',
  YELLOW: 'bg-yellow-400 shadow-yellow-400/50',
};

export const TRANSLATIONS = {
  en: {
    title: 'LUDO LEGEND',
    subtitle: 'Next-Gen Battle',
    start: 'Start Match',
    settings: 'Settings',
    roll: 'Roll Dice',
    turn: "'s Turn",
    win: 'Victory!',
    legend: 'Legend Mode',
    waiting: 'Waiting for Players...',
    aiThinking: 'AI is thinking...',
    classic: 'Classic',
    team: 'Team Mode',
    quick: 'Quick Play',
  },
  bn: {
    title: 'লুডু লেজেন্ড',
    subtitle: 'পরবর্তী প্রজন্মের লড়াই',
    start: 'ম্যাচ শুরু করুন',
    settings: 'সেটিংস',
    roll: 'ছক্কা চালুন',
    turn: '-এর চাল',
    win: 'বিজয়!',
    legend: 'লেজেন্ড মোড',
    waiting: 'খেলোয়াড়ের জন্য অপেক্ষা...',
    aiThinking: 'এআই চিন্তা করছে...',
    classic: 'ক্লাসিক',
    team: 'টিম মোড',
    quick: 'কুইক প্লে',
  },
  hi: {
    title: 'लूडो लेजेंड',
    subtitle: 'अगली पीढ़ी का खेल',
    start: 'मैच शुरू करें',
    settings: 'सेटिंग्स',
    roll: 'पासा फेंकें',
    turn: 'की बारी',
    win: 'विजय!',
    legend: 'लीजेंड मोड',
    waiting: 'खिलाड़ियों की प्रतीक्षा...',
    aiThinking: 'एआई सोच रहा है...',
    classic: 'क्लासिक',
    team: 'टीम मोड',
    quick: 'क्विक प्ले',
  },
  es: {
    title: 'LUDO LEYENDA',
    subtitle: 'Batalla Proxima Gen',
    start: 'Empezar Partida',
    settings: 'Ajustes',
    roll: 'Lanzar Dado',
    turn: 'Turno de ',
    win: '¡Victoria!',
    legend: 'Modo Leyenda',
    waiting: 'Esperando Jugadores...',
    aiThinking: 'La IA está pensando...',
    classic: 'Clásico',
    team: 'Modo Equipo',
    quick: 'Juego Rápido',
  },
};
